function aa(b,e,f,l,g){function p(){try{if(!y||0==y.length)return"";for(var a=y.length,c=Math.max.apply(null,y),d=Math.min.apply(null,y),h=0,b=0;b<a;b++)h+=y[b];return"&dvp_numts="+a+"&dvp_maxts="+c+"&dvp_mints="+d+"&dvp_avgts="+Math.round(h/a)}catch(r){return""}}function k(a,c){x=x.replace(ca[a],"&dbg"+a+"="+c)}function w(a,c){if(a instanceof Array){for(var d=0,h=a.length;d<h;d++)a[d]=a[d]+"="+c;return"&"+a.join("&")}return"&"+a+"="+c}var m=new J,q=g&&g.dvObj||window.$dv,u=g&&"undefined"!==typeof g.billable||
q&&q.tags[$uid]&&q.tags[$uid].billable,c=g&&g.impressionId||window.$uid,h=window.Nf||l,d=Array(h.gb),a=h.Va/h.bc+1,r=null,n="";b=b?b:null;f=f?f:"";var v="",C=null,D=0,Q=void 0,y=void 0,U=new RegExp(/&strp=[^&]*/),z=new RegExp(/&narme=[^&]*/),da=new RegExp(/&narm=[^&]*/),ea=new RegExp(/&naral=[^&]*/),fa=new RegExp(/&evid=[^&]*/);l=new RegExp(/&jsver=[^&]*/);for(var ga=new RegExp(/&vct=[^&]*/),ca=[new RegExp(/&dbg0=[^&]*/),new RegExp(/&dbg1=[^&]*/),new RegExp(/&dbg2=[^&]*/),new RegExp(/&dbg3=[^&]*/),
new RegExp(/&dbg4=[^&]*/),new RegExp(/&dbg5=[^&]*/),new RegExp(/&dbg6=[^&]*/),new RegExp(/&dbg7=[^&]*/),new RegExp(/&dbg8=[^&]*/),new RegExp(/&dbg9=[^&]*/),new RegExp(/&dbg10=[^&]*/),new RegExp(/&dbgtx=[^&]*/)],ha=[new RegExp(/&b0=[^&]*/),new RegExp(/&b1=[^&]*/),new RegExp(/&b2=[^&]*/),new RegExp(/&b3=[^&]*/),new RegExp(/&b4=[^&]*/),new RegExp(/&b5=[^&]*/),new RegExp(/&b6=[^&]*/),new RegExp(/&b7=[^&]*/),new RegExp(/&b8=[^&]*/),new RegExp(/&b9=[^&]*/),new RegExp(/&b10=[^&]*/),new RegExp(/&b11=[^&]*/)],
Y=Array(h.gb),t={fa:{D:null,F:null,A:null,v:null,Me:!1},j:{u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,Me:!1},Ya:{wb:null,vb:null},Eb:0},K="",L="",F,G,M="",N="",O=!1,H="",V=0;V<h.gb;V++)Y[V]="&b"+V+"=";e=function(a,c){if(a&&c)return c.replace(new RegExp(a+"=\\d*[&^#]"),"")}("prndr",e?e:null);var I=f+"?"+e,I=l.test(I)?I.replace(l,"&jsver="+b):I+"&jsver="+b,x="&naral=&narm=&narme=&dbg2=&dbg3=&dbg4=&dbg5=&dbg6=&dbg7=&dbg8=&dbg9=&dbg10=&dbgtx=&vct=",A="&strp=";e="&ctime="+(new Date).getTime();
var P=0,R="",S="",T=0,B=0,E=0,W=0;this.Tc=function(){return P};this.Lc=I+A+x+e+v+K;setEventId=function(a){C=a;x=x.replace(fa,"&evid="+C)};setAdLocatorIndicator=function(a){T=T|a;x=x.replace(ea,"&naral="+T)};setNAPMeasure=function(a){m.a("l2("+a+")");B=B|a;ia()?(setNotApplicableTime(),P=0):0==P&&(P=(new Date).getTime());x=x.replace(da,"&narm="+B);m.a("l2e")};setNAPMeasureErr=function(a){E=E|a;x=x.replace(z,"&narme="+E)};this.rd=function(a){W=W|a;x=x.replace(ga,"&vct="+W)};setBuckectStr=function(a,
c){c?v=v.replace(ha[a],"&b"+a+"="+d[a]):v=v+"&b"+a+"="+d[a]};setNotApplicableTime=function(){0!=P&&(R=(new Date).getTime()-P)};getBucketString=function(){return v};getFraudNonFraudEvents=function(a,c,d){return O?w(c,d):w(a,d)};this.mc=function(){return O};this.qd=function(a){r=a;A=A.replace(U,"&strp="+r);this.qd=function(){}};this.lb=function(){return(new Date).getTime()};var ja=this.lb();this.xe=function(){return ja};this.wf=function(){O=!0};this.uf=function(a,c){H+="&"+c.reportQueryString.viewrate+
"="+a[c.serverProperties.viewedRate]+"&"+c.reportQueryString.error+"="+a[c.serverProperties.error]+"&"+c.reportQueryString.projected+"="+(1==a[c.serverProperties.viewed]?2:a[c.serverProperties.projected]);if("undefined"===typeof a[c.serverProperties.featurebit]||a[c.serverProperties.featurebit]&&1==a[c.serverProperties.featurebit])H+="&"+c.reportQueryString.measurems+"=0",1==a[c.serverProperties.viewed]&&(H+="&"+c.reportQueryString.viewedms+"=0")};this.hf=function(){B=B&-3;E=E&-2;E&=-3};this.yb=function(){setNAPMeasure(2)};
this.sf=function(){setNAPMeasureErr(8);this.tc()};this.tc=function(){setNAPMeasure(4)};this.md=function(){setAdLocatorIndicator(8);this.yb()};this.xd=function(a){setAdLocatorIndicator(16);k(9,a)};this.yd=function(){setAdLocatorIndicator(1)};this.qf=function(){this.yb();setNAPMeasureErr(1)};this.pf=function(){this.yb();setNAPMeasureErr(2)};this.sc=function(a,c){setNAPMeasure(8);S=m.Rc(a,c)};this.lf=function(){m.a("l1");B=B&-3;setNAPMeasure(1);m.a("l1e")};this.pd=function(){setNAPMeasure(16)};this.ne=
function(){return d};this.nd=function(b,r){c=c||g&&g.impressionId||window.$uid;var n;try{c&&q&&q.tags[c]&&q.tags[c].getTimeDiff&&(n=q.tags[c].getTimeDiff())}catch(u){}var e=n-Q||100;Q=n;y?200>y.length&&y.push(e):y=[];m.a("ie15");0<=b.i&&(n=Math.floor(b.i/h.bc),0<b.i%h.bc?n++:0<b.i&&n++,isNaN(d[n])&&(d[n]=0),d[n]+=Math.max(r,e),b.J&&n>=a||0==b.J&&6<=n?D+=Math.max(r,e):timeStampTotalBuckets=D=0);m.a("ie15e")};this.ze=function(){for(var a=0,c=0;c<d.length;c++)d[c]&&(a+=d[c]);return a};this.nf=function(a){var c=
O?"false":a.$c;a="&advisonl="+(null==a.$c?"":c)+("&adabvvponl="+(null==a.Zc?"":a.Zc));k(8,"CSS1Compat"===document.compatMode?1:0);m.a("ff52");void 0!=document.documentMode&&null!=document.documentMode&&k(10,document.documentMode);m.a("ff52e");K=a};this.Za=function(a){m.a("ie14");N="&adbtftopg="+(null==a?"":O?"true":a)};this.mf=function(a){null!=a&&(t=a)};this.od=function(a){m.a("ie19");this.mf(a.K);this.vf();m.a("ie19e")};this.Bd=function(){var a;a="&vptoscrx="+(null!=t.fa.D?Math.round(t.fa.D):"");
a+="&vptoscry="+(null!=t.fa.F?Math.round(t.fa.F):"");a+="&vpwdth="+(null!=t.fa.A?Math.round(t.fa.A):"");a+="&vphgt="+(null!=t.fa.v?Math.round(t.fa.v):"");a+="&adtovpx="+(null!=t.j.u?Math.round(t.j.u):"");a+="&adtovpy="+(null!=t.j.s?Math.round(t.j.s):"");a+="&adtopgx="+(null!=t.j.G?Math.round(t.j.G):"");a+="&adtopgy="+(null!=t.j.H?Math.round(t.j.H):"");a+="&adtoscrx="+(null!=t.j.B?Math.round(t.j.B):"");a+="&adtoscry="+(null!=t.j.C?Math.round(t.j.C):"");a+="&scrwdth="+(null!=t.Ya.wb?Math.round(t.Ya.wb):
"");a+="&scrhgt="+(null!=t.Ya.vb?Math.round(t.Ya.vb):"");return a+="&almesind="+t.Eb};this.Cd=function(){var a="";if(F&&G){var c=null!=t.j.o?t.j.o:null,d=null!=t.j.m?t.j.m:null;0>F*G&&(a+="&dvp_adwdth="+F,a+="&dvp_adhgt="+G,F=c,G=d)}else F=null!=t.j.o?t.j.o:null,G=null!=t.j.m?t.j.m:null;a+="&adwdth="+(null!=F?F:"");return a+="&adhgt="+(null!=G?G:"")};this.vf=function(){setNotApplicableTime();v="";for(var a=0;a<d.length;a++)d[a]&&(v+=Y[a]+d[a]);L=this.Cd();M=K+this.Bd()+L;M+=N;this.Lc=I+A+x+v+M};this.Qc=
function(){return 1E3<=D};this.ba=function(a){c=c||g&&g.impressionId||window.$uid;var d=I+"&impid="+c,h=-1,b=m.ob();try{q&&q.tags[c]&&q.tags[c].getTimeDiff&&(h=q.tags[c].getTimeDiff())}catch(r){}switch(a){case 1:n=h;d+=A+x+"&napt="+R+M+b+"&napr="+S;b="";u&&(b=g.Ua?getFraudNonFraudEvents(["isbmms"],"isfbmms",h):getFraudNonFraudEvents(["isbmms","isgmmims"],"isfbmms",h));d+=b+getFraudNonFraudEvents("ismms","isfmms",h)+"&isumms="+h;break;case 2:d+=A+x+"&napt="+R+M+b+"&napr="+S+getFraudNonFraudEvents("isnmms",
"isfnmms",h);break;case 3:d+="&istoms="+h;case 4:case 8:d+=A+N+L+"&isbxdms="+h+(O?"&fbxdtb="+this.ze():v)+p();break;case 5:n=n||h;d+=A+N+L+K+getFraudNonFraudEvents("isiabvms","isfiabvms",h)+"&isuiabvms="+h+getFraudNonFraudEvents("ismms","isfmms",n)+"&isumms="+n+p();break;case 6:n=n||h;d+=N+L+K+getFraudNonFraudEvents("iscvmvms","isfcvmvms",h)+getFraudNonFraudEvents("ismms","isfmms",n)+p();break;case 16:d+=A+x+"&napt="+R+b+"&napr="+S+"&ishems="+h;break;case 7:return d;case 9:d+=H;break;case 10:d+="&ismms=0";
break;case 17:n=n||h;b=g.Ua?["isbmms"]:["isbmms","isgmmims"];d+=A+N+L+K+getFraudNonFraudEvents(g.Ua?["isbvms"]:["isbvms","isgmpims"],"isfbvms",h)+getFraudNonFraudEvents(b,"isfbmms",n);break;default:d=this.Lc+"&napt="+R+"&ctime="+this.lb()+b+"&napr="+S}return d+"&evid="+a+"&ctime="+this.lb()};this.me=function(){m.a("ie17");for(var a=[],c=0;c<h.gb;c++)a[c]=d[c]?d[c]:0;return a};var ia=this.Ub=function(){return 2==(B&2)&&8!=(T&8)||4==(B&4)||8==(E&8)&&8==(T&8)?!1:!0};this.cf=function(a){m.a("l3");a=m.la(a);
m.a("cm3e");a&&(k(5,a.w),k(6,a.h));m.a("l3e")};return this}
function ba(b,e){this.window=null;this.ib={};this.images={};this.Cb=this.S=function(b){navigator.sendBeacon(b,{})};this.window=b;"function"!=typeof navigator.sendBeacon&&(this.Xb=function(b){var e=this.window.document.createElement("img");e.name=e.id=b;e.width=0;e.height=0;e.style.display="none";e.src="";this.window.document.body.insertBefore(e,this.window.document.body.firstChild);return e},this.Cb=function(b,e){if(e&&1!=this.ib[e]||16==e)this.images[e]?(this.images[e].src=b,this.ib[e]=1):this.S(b,
e)},this.S=function(b,e){if(e&&1!=this.ib[e]||16==e||7==e)this.window.document.createElement("img").src=b,this.ib[e]=1},this.window&&(this.images={3:this.Xb(e+"_13"),4:this.Xb(e+"_14"),8:this.Xb(e+"_18")}));return this}function X(){this.Cb=function(){};this.S=function(){}}
function ka(b,e,f,l){function g(){if(1==v){try{for(var a in r)n.removeChild(r[a]);d.document.body.removeChild(n)}catch(c){}v=!1}}function p(a){a=a||0;var c=m(0);c.cd()?7<c.nb()?(g(),D=C=v=!1):(v=!0,C=!1):20>a?(a++,setTimeout(p,50,a)):(v=C=D=!1,g())}function k(a){$dv&&$dv.tags&&$dv.tags[l]&&$dv.tags[l].getTimeDiff&&$dv.tags[l].getTimeDiff();if(null!==a.cb)for(var c=0;c<a.cb.length;c++){var d=m(c).nb();0==c?d>Q&&(Q=d):d>y&&(y=d)}}function w(a){for(var c=!0,d=0;13>=d;d++)var h=m(d),c=c&(null!==h&&h.cd());
if(!c)return null;a.Gc=0;a.pc=0;a.oc=0;a.jc=0;a.Ba=0;a.cb=Array(13);c=m(0).nb();for(d=1;13>=d;d++)if(h=5<Math.abs(m(d).nb()-c),a.cb[d]=h)switch(a.Gc++,d){case 2:case 3:case 4:case 5:a.pc++;break;case 6:case 7:case 8:case 9:a.oc++;break;case 10:case 11:case 12:case 13:a.jc++}if(13===a.Gc)return a.Ba=100,k(a),!0;c=a.cb;if(!1===c[1]){if(3<=a.jc||3<=a.oc||3<=a.pc)return k(a),null;a.Ba=0;k(a);return!1}if(!0===c[1]&&(!0===c[2]&&!0===c[3]||!0===c[2]&&!0===c[4]||!0===c[3]&&!0===c[5]||!0===c[4]&&!0===c[5])||
!0===c[1]&&4==a.oc||!0===c[1]&&4==a.jc&&1<=a.pc)return a.Ba=50,k(a),!0;if(c[2]&&c[5]&&!(c[6]&&c[10]&&c[1]&&c[13]&&c[9])||c[4]&&c[3]&&!(c[8]&&c[12]&&c[1]&&c[11]&&c[7]))return k(a),null;a.Ba=0;k(a);return!1}function m(a){a=r[a];var c=null;a&&(c=a.contentWindow);return c}function q(){for(var d=a.getBoundingClientRect(),h=d.width,b=d.height,n=h/(1+c),e=b/(1+c),q=h/c,u=b/c,v=0;13>=v;v++){var g=d.left,f=d.top;switch(v){case 0:f=g=-1E5;break;case 1:g+=(h-1)/2;f+=(b-1)/2;break;case 3:g+=h-1;break;case 4:f+=
b-1;break;case 5:g+=h-1;f+=b-1;break;case 6:g+=(h-q)/2;f+=(b-u)/2;break;case 7:g+=(h-q)/2+q;f+=(b-u)/2;break;case 8:g+=(h-q)/2;f+=(b-u)/2+u;break;case 9:g+=(h-q)/2+q;f+=(b-u)/2+u;break;case 10:g+=(h-n)/2;f+=(b-e)/2;break;case 11:g+=(h-n)/2+n;f+=(b-e)/2;break;case 12:g+=(h-n)/2;f+=(b-e)/2+e;break;case 13:g+=(h-n)/2+n,f+=(b-e)/2+e}6<=v&&(g-=.5,f-=.5);var k=r[v];k.style.left=g+"px";k.style.top=f+"px"}}function u(){if(null!=a&&null!=a.parentNode){C=!0;n=d.document.createElement("div");d.document.body.appendChild(n);
for(var c=0;13>=c;c++){var h=d.document.createElement("iframe");h.width=1;h.height=1;h.style.position="absolute";h.frameBorder="0";h.style.visibility="hidden";h.style.zIndex=-9999999;h.style.display="block";h.src="javascript:no=false;yes=true;("+function(){window.Ue={Yd:100};window.Nc=no;window.ab=0;window.Oc=0;window.Yc=0;window.Of=no;window.nb=function(){return window.Yc};window.cd=function(){return window.Nc};window.Se=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;window.Tb=function(){window.ab++;window.Se(window.Tb,document)};window.Tb();setInterval(function(){10>window.ab&&window.Tb();window.Yc=window.ab-window.Oc;window.Oc=window.ab},window.Ue.Yd);window.setTimeout(function(){window.Nc=yes},250)}.toString()+")();";n.appendChild(h);r.push(h)}q()}}var c=Math.sqrt(2),h=new J,d=null,a=null,r=[],n,v=!1,C=!1,D=h.tb(b,e,f),Q=0,y=0;this.Je=function(){0==C&&(0==(this.Ta()&&(null!=a&&h.bd(a,d)?!0:!1))?v=!1:(u(),p()))};this.Ta=function(){return D};
this.Pe=function(){return v};this.sd=function(c,h){d=c;a=h;this.Je()};this.Be=function(){if(0==v)return null;var a={};return null==w(a)?null:a.Ba}}
function la(b,e,f,l,g,p,k,w){this.b=new J;this.window=b;this.f=e;this.V=f;this.I=l;this.Y=k&&k.Enums.BrowserId||window.$dv.Enums.BrowserId;this.ea=k&&k.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario;this.P=g;this.hc=p;this.ha=null;this.ha=new ka(this.V,this.I,k,w);null!=this.ha&&this.ha.Ta()&&this.ha.sd(this.window,this.f);this.pb=this.ub=this.ra=null;this.qb=!1;var m=0;this.ja={Od:1,Pd:2,Id:4,Kb:8,Hd:16,Lb:32,Nd:64};this.rc=function(b,e,c,h){if(h&&h.insertBefore&&h.firstChild&&(b=this.window.document.createElement(b))){for(var d in e)b[d]=
e[d];for(d in c)b.style[d]=c[d];h.insertBefore(b,h.firstChild);return b}return null};this.dc=function(b,e,c){var h=e.A;e=e.v;var d=0,a=0,r=b.right-b.left,n=b.bottom-b.top;if(0>b.bottom||0>b.right||b.top>e||b.left>h||0>=r||0>=n)return 0;0>b.top?Math.abs(b.top)>=n?d=n:(d=n+b.top,d>e&&(d=e)):d=b.top+n>e?e-b.top:n;0>b.left?Math.abs(b.left)>=r?a=r:(a=r+b.left,a>h&&(a=h)):a=b.left+r>h?h-b.left:r;return 0>=a||0>=d?0:Math.round(a*d/(r*n)*(c?r*n/((c.right-c.left)*(c.bottom-c.top)):1)*100)};this.cc=function(b,
e){try{var c={x:b.offsetLeft,y:b.offsetTop};if(b.offsetParent){var h=this.cc(b.offsetParent,e);c.x+=h.x;c.y+=h.y}else e!=e.parent&&this.b.Mb(e,e.parent)&&(h=this.cc(e.frameElement,e.parent),c.x+=h.x,c.y+=h.y);return c}catch(d){return{x:null,y:null}}};this.oa=function(b){if(this.V==this.ea.CrossDomain)if(this.b.xa(this.window)&&this.window.$sf.ext.geom)this.oa=function(){var a=this.b.Ia(this.window),c=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(a.win.h):
this.P.Explorer.Z,d={A:null,v:null,D:null,F:null,g:!1};d.A=parseInt(a.win.w);d.v=parseInt(a.win.h);d.D=parseInt(a.win.l);d.F=parseInt(a.win.t)+c;d.g=!0;return d};else if(this.I.X==this.Y.Firefox)this.oa=function(){var a=8==screen.top-this.window.screenY&&8==screen.left-this.window.screenX,c=a?0:this.window.screenX-screen.left,a=a?0:this.window.screenY-screen.top,d={A:null,v:null,D:null,F:null,g:!1};d.A=this.window.outerWidth;d.v=this.window.outerHeight-this.P.Firefox.Z;d.D=c;d.F=a+this.P.Firefox.Z;
d.g=!0;return d};else if(this.b.lc(this.window)){var e=this;this.window.context.observeIntersection(function(a){a.forEach(function(a){e.ra=a})});this.oa=function(){var a={A:null,v:null,g:!1,D:null,F:null};null!=this.ra?(a.A=this.ra.rootBounds.width,a.v=this.ra.rootBounds.height):(a.A=0,a.v=0);a.g=!0;return a}}else if(this.I.X==this.Y.IE&&/^[11|12]/.test(this.I.wa))this.oa=function(){var a=-8==this.window.screenY&&-8==this.window.screenX,c=a?0:this.window.screenX,a=a?0:this.window.screenY,d={A:null,
v:null,D:null,F:null,g:!1};d.A=this.window.outerWidth;d.v=this.window.outerHeight-this.P.Explorer.Z;d.D=c;d.F=a+this.P.Explorer.Z;d.g=!0;return d};else if(this.I.X==this.Y.IE&&/[6-9]|[10]/.test(this.I.wa)){var c=this.rc("iframe",{name:"dv_ie9onload",src:"",width:0,height:0,ge:0,Ve:"0",We:"0"},{display:"inline",position:"absolute",top:0,left:0,Bf:"none",zIndex:0,border:0},this.window.document.body),h=this.rc("iframe",{name:"dv_ie9onmousemove",src:"",width:0,height:0,ge:0,Ve:"0",We:"0"},{display:"inline",
position:"absolute",top:0,left:0,Bf:"none",zIndex:0,border:0},this.window.document.body),d=h.contentWindow||h.window||h.contentDocument.window||h.contentWindow.window||this.window.Ef,a=c.contentDocument||c.contentWindow.document,c=h.contentDocument||h.contentWindow.document,r="<html><head><script >window.onload = "+function(a){a&&(window.event=a);isFinite(String(window.event.clientY))&&(parent.Pa={Pb:window.event.clientY,Ob:window.event.clientX,Ad:window.event.screenY-window.event.clientY-window.screenY})}.toString()+
"; \x3c/script></head><body></body></html>",h='<html><head></head><body><script > function runMoM(){ window.document.body.fireEvent("onmousemove");} window.document.body.onmousemove = '+function(a){a&&(window.event=a);isFinite(String(window.event.clientY))&&(parent.sa={Pb:window.event.clientY,Ob:window.event.clientX,Ea:window.event.screenY-window.event.y,Da:window.event.screenX-window.event.x})}.toString()+"; runMoM();\x3c/script></body></html>";c.open("text/html","replace");c.write(h);c.close();
a.open("text/html","replace");a.write(r);a.close();("CSS1Compat"===document.compatMode?this.window.document.documentElement:this.window.document.body).clientLeft;this.oa=function(){d.runMoM();a.open("text/html","replace");a.write(r);a.close();var c=this.window.sa,h=this.window.Pa,b=screen.availWidth,e=screen.availHeight,h=h?h.Ad:this.P.Explorer.Z;if(c){var g=c.Da,f=c.Ea;c.Da>=b&&(c.Da-=b);c.Ea>=e&&(c.Ea-=e);var u={A:null,v:null,D:null,F:null,g:!1};u.A=this.window.outerWidth?this.window.outerWidth-
20:b-c.Da-20;u.v=this.window.outerHeight?this.window.outerHeight-h-10:e-c.Ea-10;u.D=g;u.F=f;u.g=!0}else u={A:null,v:null,D:null,F:null,g:!1},u.A=this.window.outerWidth?this.window.outerWidth-20:b-20,u.v=this.window.outerHeight?this.window.outerHeight-h-10:e-10,u.D=null,u.F=null,u.g=!1;return u}}else this.b.sb()?(this.kd(),this.oa=function(){this.qb||this.kd();var a={A:null,v:null,D:null,F:null,g:!1};a.A=this.window.outerWidth;a.v=this.window.outerHeight-this.P.Chrome.Z;a.g=!1;return a}):this.oa=this.I.X==
this.Y.Chrome?function(){var a={A:null,v:null,D:null,F:null,g:!1},c=!1;try{a.A=this.window.frameElement.offsetParent.parentNode.clientWidth,a.v=this.window.frameElement.offsetParent.parentNode.clientHeight,c=!0}catch(d){}a.D=this.window.screenX;a.F=this.window.screenY;a.g=c;return a}:null!=this.ha&&this.ha.Ta()?function(){var a={A:null,v:null,D:null,F:null,g:!1};a.A=this.window.outerWidth;a.v=this.window.outerHeight-this.P.Safari.Z;a.g=!1;return a}:function(){return{A:null,v:null,D:null,F:null,g:!1}};
else this.oa=function(){var a,c,d=this.window.top;void 0!=d.mozInnerScreenX&&null!=d.mozInnerScreenX?(a=d.mozInnerScreenX,c=d.mozInnerScreenY):void 0!=d.screenX&&null!=d.screenX?0!=d.screenLeft+8&&d.screenLeft+8!=screen.width||0!=d.screenTop+8&&d.screenTop+8!=screen.height?(a=d.screenLeft,c=d.screenTop+(d.outerHeight-d.innerHeight)):(a=d.screenLeft+8,c=d.screenTop+(d.outerHeight-d.innerHeight)+8):(a=d.screenLeft,c=d.screenTop);var h={A:null,v:null,D:null,F:null,g:!1},b=this.b.Qa(d);h.A=d.innerWidth||
b.clientWidth;h.v=d.innerHeight||b.clientHeight;h.D=a;h.F=c;h.g=!0;return h};return this.oa(b)};this.na=function(b,e){m=1;this.V==this.ea.CrossDomain?this.b.xa(this.window)&&this.window.$sf.ext.geom&&this.b.Ia(this.window).par?(m=8,this.na=function(){var c=this.b.Ia(this.window),h=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(c.win.h):this.P.Explorer.Z,d={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,O:null,qa:null};
d.u=parseInt(c.self.l)-parseInt(c.par.l);d.s=parseInt(c.self.t)-parseInt(c.par.t);d.G=parseInt(c.self.l);d.H=parseInt(c.self.t);d.B=parseInt(c.win.l)+d.u;d.C=parseInt(c.win.t)+d.s+h;d.o=parseInt(c.self.w);d.m=parseInt(c.self.h);d.g=!0;d.rect={top:d.s,bottom:d.s+d.m,left:d.u,right:d.u+d.o};return d}):this.I.X==this.Y.Firefox?this.na=function(){var c=1;window.devicePixelRatio&&(c=window.devicePixelRatio);var h=this.window.screenX,d=this.window.screenY,a=this.window.mozInnerScreenX/c-h,c=this.window.mozInnerScreenY/
c-d-this.P.Firefox.Z,a={left:a,top:c,right:a+this.window.innerWidth,bottom:c+this.window.innerHeight},c={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,O:null,qa:null};c.u=a.left;c.s=a.top;c.G=null;c.H=null;c.B=h+a.left;c.C=d+a.top;c.o=this.window.innerWidth;c.m=this.window.innerHeight;c.g=!0;c.rect=a;this.b.Db()&&(c=this.jb(c));return c}:this.b.lc(this.window)?(m=32,this.na=function(){var c={u:null,s:null,o:null,m:null,g:!1,rect:null,O:null,qa:null,G:null,H:null,B:null,C:null};
null!=this.ra?(c.u=this.ra.boundingClientRect.left,c.s=this.ra.boundingClientRect.top,c.o=this.ra.boundingClientRect.width,c.m=this.ra.boundingClientRect.height):(c.u=0,c.s=0,c.o=0,c.m=0);c.g=!0;c.rect={top:c.s,bottom:c.s+c.m,left:c.u,right:c.u+c.o};return c}):this.I.X==this.Y.IE&&/^[11|12]/.test(this.I.wa)?this.na=function(c){var h=this.window.screenLeft-window.screenX,d=this.window.screenTop-window.screenY-this.P.Explorer.Z,h={left:h,top:d,right:h+this.window.innerWidth,bottom:d+this.window.innerHeight},
d={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,O:null,qa:null};d.u=h.left;d.s=h.top;d.G=null;d.H=null;d.B=c.D+h.left;d.C=c.F+h.top;d.o=this.window.innerWidth;d.m=this.window.innerHeight;d.g=!0;d.rect=h;this.b.Db()&&(d=this.jb(d));return d}:this.I.X==this.Y.IE&&/[6-9]|[10]/.test(this.I.wa)?this.na=function(){if(8==document.documentMode)return{u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,O:null,qa:null};var c=this.window.Pa&&this.window.sa?this.window.Pa.Pb-
this.window.sa.Pb:0,h=this.window.Pa&&this.window.sa?this.window.Pa.Ob-this.window.sa.Ob:0,d=this.b.Qa(this.window),a={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,O:null,qa:null};a.u=h;a.s=c;a.G=null;a.H=null;a.B=this.window.sa?h+this.window.sa.Da:null;a.C=this.window.sa?c+this.window.sa.Ea:null;a.o=this.window.innerWidth||d.clientWidth;a.m=this.window.innerHeight||d.clientHeight;a.g=!0;a.rect={left:h,top:c,right:h+(this.window.innerWidth||d.clientWidth),bottom:c+(this.window.innerHeight||
d.clientHeight)};this.b.Db()&&(a=this.jb(a));return a}:this.b.sb()?(m=512,this.na=function(){var c={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,O:null,qa:null};null!=this.f&&(adData=this.b.mb(this.f),c.o=adData?adData.w:this.window.innerWidth,c.m=adData?adData.h:this.window.innerHeight);return c}):this.na=this.I.X==this.Y.Chrome?function(){var c=null,h=null,d=!1;try{var a=this.window.frameElement.offsetTop,c=this.window.frameElement.offsetLeft-this.window.frameElement.offsetParent.scrollLeft,
h=a-this.window.frameElement.offsetParent.scrollTop,d=!0}catch(b){}a={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,O:null,qa:null};a.u=c;a.s=h;a.G=null;a.H=null;a.B=null;a.C=null;a.o=this.window.innerWidth;a.m=this.window.innerHeight;a.g=d;a.rect=d?{left:c,top:h,right:c+this.window.innerWidth,bottom:h+this.window.innerHeight}:null;this.b.Db()&&(a=this.jb(a));return a}:null!=this.ha&&this.ha.Ta()?function(){var c={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,
rect:null,O:null,qa:null};null!=this.f&&(adData=this.b.mb(this.f),c.o=adData?adData.w:this.window.innerWidth,c.m=adData?adData.h:this.window.innerHeight);return c}:function(){return{u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,O:null,qa:null}}:this.na=function(c){var h=this.cc(this.f,this.window),d={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,O:null,qa:null},a=this.b.ec(this.f,this.window),b=this.b.zc(this.f,this.window);d.u=b.left;d.s=b.top;d.G=
h.x;d.H=h.y;d.B=c.D+b.left;d.C=c.F+b.top;d.o=b.w;d.m=b.h;d.g=!0;d.rect=a;d.O=b;return d};return this.na(b,e)};this.jb=function(b){if(this.window.document.body==this.f||this.window.document.documentElement==this.f)return b;var e=this.b.mb(this.f);if(e){var c=e.w,h=e.h,d=b.u,a=b.s,r=b.C,g=b.B;null!=b.u&&null!=b.s&&null!=b.m&&null!=b.o&&b.rect&&(0<e.t?(a=b.s+e.t,null!=b.C&&(r=b.C+e.t)):h+=e.t,0<e.l?(d+=e.l,null!=b.B&&(g=b.B+e.l)):c+=e.l,e.r>b.o&&(c-=e.r-b.o),e.Fc>b.m&&(h-=e.Fc-b.m),b.o=0<c?c:0,b.m=0<
h?h:0,b.u=d,b.s=a,b.C=r,b.B=g,b.rect.left=b.u,b.rect.top=b.s,b.rect.right=b.u+e.w,b.rect.bottom=b.s+e.h,b.O={w:c,h:h,left:d,right:d+c,top:a,bottom:a+h})}return b};this.we=function(){var b=screen.availLeft||0;return{g:$dv.CommonData&&$dv.CommonData.deviceType&&1==$dv.CommonData.deviceType?"undefined"!==typeof b:!1,wb:screen.availWidth||screen.width,vb:screen.availHeight||screen.height,Lf:b,Mf:screen.availTop||0}};this.je=function(){var b=this.we(),e=this.oa(b),c=this.na(e,b);return{fa:e,j:c,Ya:b,Eb:(null==
e.D||null==e.F?0:this.ja.Od)|(null==e.A||null==e.v?0:this.ja.Pd)|(null==c.u||null==c.s?0:this.ja.Id)|(null==c.G||null==c.H?0:this.ja.Kb)|(null==c.B||null==c.C?0:this.ja.Hd)|(null==c.m||null==c.o?0:this.ja.Lb)|(null==b.vb||null==b.wb?0:this.ja.Nd),J:this.Kc(c.m,c.o)}};this.Kc=function(b,e){null==b&&(b=0);null==e&&(e=0);return 242500<=b*e?!0:!1};this.re=function(){this.b.a("c10");if(null!=this.f)if(this.b.bd(this.f,this.window))try{var b={timeStamp:new Date,i:-3,ka:-3,K:null,J:!1,ga:0};if(!this.hc())return b;
var e=this.je();if(!e.j.g||!e.fa.g){if(this.b.xa(this.window)&&this.window.$sf.ext.inViewPercentage){var c=this.window.$sf.ext.inViewPercentage();return{timeStamp:new Date,i:c,ka:c,K:e,J:e.J,ga:16}}if(this.b.sb()&&this.qb)return c=0,null!=this.pb&&(c=Math.round(100*this.pb.intersectionRatio)),{timeStamp:new Date,i:c,ka:c,K:e,J:this.Kc(e.j.m,e.j.o),ga:512};if(this.ha.Ta()){var h={timeStamp:new Date,i:-3,ka:-3,K:null,J:!1,ga:2};if(0==this.ha.Pe())h.i=-6,h.ka=-6,this.ha.sd(this.window,this.f);else{var d=
this.ha.Be();null!=d&&(h.K=e,h.J=e.J,h.i=d,h.ka=d)}return h}b.K=e;m&&(b.ga=m);return b}if(e.j&&e.j.O&&(0===e.j.O.w||1===e.j.O.w||0===e.j.O.h||1===e.j.O.h))return{timeStamp:new Date,i:-5,ka:-5,K:e,ga:m};c=e.j.O?this.dc(e.j.O,e.fa,e.j.rect):this.dc(e.j.rect,e.fa);return{timeStamp:new Date,i:c,ka:c,K:e,J:e.J,ga:m}}catch(a){return{timeStamp:new Date,i:-4,ka:-4,K:null,J:!1,ga:m}}else return{timeStamp:new Date,i:-2,ka:-2,K:null,J:!1,ga:0};else return{timeStamp:new Date,i:-1,ka:-1,K:null,J:!1,ga:0}};this.ke=
function(b,e){this.b.a("c11");var c=null,h=null;if(null!=b.K){var d=b.K.j;e<=this.P.Ze&&(c=0<=b.i||-5==b.i?b.J&&b.i>=this.P.Va||0==b.J&&50<=b.i?!0:!1:null,h=b.J?this.P.Va/100:.5,h=0==c?0>d.s+d.m*h?!0:!1:1==c?!1:null)}return{Zc:h,$c:c}};this.rb=function(b){this.b.a("c12");var e=null;if(2!=b.ga&&512!=b.ga&&null!=b.K){var c=b.K.Eb,h=b.K.j;(c&this.ja.Kb)==this.ja.Kb&&(c&this.ja.Lb)==this.ja.Lb&&(e=this.dc({left:h.G,top:h.H,right:h.G+h.o,bottom:h.H+h.m},b.K.fa,h.rect),e=0<=b.i?b.J&&e>=this.P.Va||0==b.J&&
50<=e?!1:!0:null)}this.b.a("c12e");return e};this.kd=function(){function b(c){c.forEach(function(c){e.pb=c})}var e=this;"undefined"!=typeof IntersectionObserver&&null!=this.f&&(m=512,this.ub=new IntersectionObserver(b,{threshold:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1]}),this.ub.observe(this.f),this.qb=!0)};this.Ie=function(){this.f=null;null!=this.ub&&(this.ub.disconnect(),this.pb=null,this.qb=!1)}}
function J(){this.getElementVolume_object=function(b){var e=b.getAttribute("width"),f=b.getAttribute("height");null==e||""==e||null==f||""==f?(b=b.parentNode,b={w:b.clientWidth,h:b.clientHeight}):b={w:e,h:f};return b};this.Qe=function(b){var e=0;try{for(;null!=b&&10>e;){if("none"==window.getComputedStyle(b).display||"hidden"==window.getComputedStyle(b).visibility)return!1;b=b.parentElement;e++}}catch(f){}return!0};this.la=function(b,e){this.a("cm1");var f=null,l=b.nodeName.toLowerCase();e&&this["getElementVolume_"+
l]&&(f=this["getElementVolume_"+l](b));if(!f&&(f=this.mb(b),this.a("cm2e"),!f||1>=f.w||1>=f.h))return this.a("cm1e"),{w:0,h:0};f.w.indexOf&&f.w.indexOf("px")&&(f.w=f.w.replace("px",""));f.h.indexOf&&f.h.indexOf("px")&&(f.h=f.h.replace("px",""));this.a("cm1e");return f};this.mb=function(b){this.a("cm2");try{var e;return document.body.getBoundingClientRect&&(e=b.getBoundingClientRect())?{w:e.right-e.left,h:e.bottom-e.top,l:e.left,t:e.top,Fc:e.bottom,r:e.right}:null}catch(f){return null}};this.Qa=function(b){this.a("ff8");
b=b.document.documentElement.clientHeight?b.document.documentElement:b.document.body;this.a("ff8e");return b};this.Sc=function(b,e){this.a("ff9");var f=0,l=!1;if(b.document.all)for(var g=0;g<b.document.all.length;g++)"BODY"==b.document.all[g].nodeName&&(l=!0),l&&("width"==e?b.document.all[g].width>f&&(f=b.document.all[g].width):b.document.all[g].height>f&&(f=b.document.all[g].height));this.a("ff9e");return f};this.fd=function(b,e){for(var f=this.Qa(b),l=b.innerWidth||f.clientWidth||this.Sc(b,"width"),
f=b.innerHeight||f.clientHeight||this.Sc(b,"height"),g=e.length,p=0,k=0;k<g;k++)if(15>=Math.abs(l-e[k].w)){p=e[k].h.length;for(l=0;l<p;l++)if(15>=Math.abs(f-e[k].h[l]))return!0;break}return!1};this.xf=function(b){for(var e=[],f=-1;e[++f]=b[f];);e.length--;return e};this.Hb=function(b,e,f,l){var g=b.getElementsByTagName("*"),g=this.xf(g);g.unshift(b);for(var p=["EMBED","IFRAME","OBJECT","IMG","DIV"],k=[],w=0;w<g.length;w++){var m=g[w];if(-1!=p.indexOf(m.nodeName)){var q=l(m);q&&k.push({Ec:q.w*q.h,
w:q.w,h:q.h,type:m.nodeName||"other",fe:m})}}k=k.sort(function(b,c){return c.Ec-b.Ec||p.indexOf(c.type)-p.indexOf(b.type)});(e=0<k.length&&k[0].w>e&&k[0].h>f?k[0].fe:null)&&b&&(e.ic=b.ic);return e};this.bd=function(b,e){this.a("ff10");try{if(!b)return!1;for(e||(e=window);b!=e.document&&b.parentNode;)b=b.parentNode;this.a("ff10e");return b==e.document}catch(f){return!1}};this.ec=function(b,e){var f=e.parent,l={left:0,right:0,top:0,bottom:0};if(b){var g=b.getBoundingClientRect();e!=f&&this.Mb(e,f)&&
(l=this.ec(e.frameElement,f));l={left:g.left+l.left,right:g.right+l.left,top:g.top+l.top,bottom:g.bottom+l.top}}return l};this.Mb=function(b,e){var f=!1;if(b==e)f=!0;else try{b.document.domain==e.document.domain&&(f=!0)}catch(l){}return f};this.se=function(b){if(b)try{if(b.contentDocument&&this.ad(b.contentDocument))return b.contentDocument;if(b.contentWindow&&this.ed(b.contentWindow))return b.contentWindow.document}catch(e){}return null};this.Ee=function(b){return b?b.defaultView||b.parentWindow:
null};this.Le=function(b,e){return-1<e.indexOf(b)};this.le=function(b){try{return b!=b.top&&b.parent&&this.ed(b.parent)?b.parent:null}catch(e){return null}};this.ed=function(b){try{return b&&b.document&&this.ad(b.document)?!0:!1}catch(e){return!1}};this.ad=function(b){try{return b&&b.getElementsByTagName&&b.getElementById?!0:!1}catch(e){return!1}};this.zc=function(b,e){var f=e.parent,l={w:0,h:0,left:0,right:0,top:0,bottom:0};b&&(l=this.ec(b,e),l.w=l.right-l.left,l.h=l.bottom-l.top,e!=f&&this.Mb(e,
f)&&(f=this.zc(e.frameElement,f),f.bottom<l.bottom&&(f.bottom<l.top&&(l.top=f.bottom),l.bottom=f.bottom),f.right<l.right&&(f.right<l.left&&(l.left=f.right),l.right=f.right),l.w=l.right-l.left,l.h=l.bottom-l.top));return l};this.Wb=function(b,e){return function(){return b.apply(e,arguments)}};this.ta=function(b){try{return b?b.length?b.length:0:0}catch(e){return 0}};this.gc=function(b){for(var e=[],f=0;f<b.length;f++)this.Qe(b[f])&&e.push(b[f]);return e};this.a=function(b){try{maxLength=3,$dv&&($dv.Ja=
$dv.Ja||[],$dv.Ja.push(b),$dv.Ja.length>maxLength&&$dv.Ja.shift())}catch(e){}};this.ob=function(){try{return $dv&&$dv.Ja?"&dvp_log="+$dv.Ja.join():""}catch(b){return""}};this.xa=function(b){if(b.$sf&&b.$sf.ext)if(b.$sf.ext.geom){if(b=this.Ia(b),null!=b&&b.win&&(0<b.win.h||0<b.win.w))return this.xa=function(){return!0},!0}else if(b.$sf.ext.inViewPercentage)return!0;this.xa=function(){return!1};return!1};this.Ia=function(b){b.$sf.ext.geom&&(this.Ia="function"==typeof b.$sf.ext.geom?function(b){return b.$sf.ext.geom()}:
function(b){return b.$sf.ext.geom});return this.Ia(b)};this.lc=function(b){return b.context&&b.context.observeIntersection?!0:!1};this.sb=function(){var b=!1;if(1==this.kb("disableIO"))return!1;"undefined"!=typeof IntersectionObserver&&(b=!0);return b};this.tb=function(b,e,f){var l=f&&f.Enums.BrowserId||window.$dv.Enums.BrowserId;if(b==(f&&f.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario).CrossDomain&&e.X===l.Safari&&(null===e.wa||void 0===e.wa||!/^[3-8]/.test(e.wa)))return this.tb=function(){return!0},
!0;this.tb=function(){return!1};return!1};this.kb=function(b){var e,f=this.Pc();f&&f.AVO&&(e=f.AVO[b]);return e};this.Pc=function(){var b={},e=window.$dv,f=window.$uid;e.tags&&e.tags[f]&&(b=e.tags[f]);return b};this.Db=function(){return 1==this.kb("sam")?!0:!1};this.Sa=function(b){return b.document.hasFocus()};this.Ha=new function(){var b=this;b.cache=[];window.addEventListener?b.add=function(e,f,l,g,p){if("undefined"==typeof g||null==g)g=window;g.addEventListener(e,f,l);p&&b.cache.push([e,f,l,g])}:
window.attachEvent?b.add=function(e,f,l,g,p){if("undefined"==typeof g||null==g)g=window;g["e"+e+f]=f;g[e+f]=function(){g["e"+e+f](window.event)};g.attachEvent("on"+e,g[e+f]);p&&b.cache.push([e,f,l,g])}:b.add=function(){};window.removeEventListener?b.remove=function(b,f,l,g){if("undefined"==typeof g||null==g)g=window;g.removeEventListener(b,f,l)}:window.detachEvent?b.remove=function(b,f,l,g){if("undefined"==typeof g||null==g)g=window;g.detachEvent("on"+b,g[b+f]);g[b+f]=null;g["e"+b+f]=null}:b.remove=
function(){};b.flush=function(){for(var e=0;e<b.cache.length;e++)b.remove.apply(b,b.cache[e]);b.cache=[]}};this.Rc=function(b,e){var f=b||"",l="";if(e&&(f+=": "+(e.message||""),e.stack)){var l=e.stack||"",g=l.indexOf("at ");0>g&&(g=0);l=", Stack: "+l.slice(g,l.length)}f=f.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"");l=l.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"").replace(/    at/g,"at").replace(/\?/g,"-").replace(/&/g,"-");g=null;try{g=encodeURIComponent(f+
l).slice(0,500)}catch(p){try{g=encodeURIComponent(f).slice(0,500)}catch(k){g=f.slice(0,500)}}return g}}
function ma(b,e,f,l,g){function p(c,b){for(var d=[],a=0;a<m.length;a++){var e=[],e=b(c,m[a]),g=k.ta(e);if(0!=g){var f=k.Ee(m[a]);if(null!=f)for(var l=0;l<g;l++)try{e[l].ic=f,d.push(e[l])}catch(u){}}}return d}var k=new J,w="Microsoft Internet Explorer"==navigator.appName;this.c=l;this.window=f;this.Fb=[["DCF",'"'],[";",";"],["%3B","%3B"],["zoneid=","_"],["zoneid%3D","_"],["PRImpID=",""],["PRImpID%3D",""],["PRPID=",""],["PRPID%3D",""]];this.qc=[1==w?"object":"embed",1==w?"embed":"object","href","img",
"span","iframe","frameElement","div"];this.Ab=this.f=null;this.dataObj=b;this.dvObj=b.dvObj||window.$dv;this.I={X:this.dvObj.CommonData.BrowserId,wa:this.dvObj.CommonData.BrowserVersion};this.Y=this.dvObj.Enums.BrowserId;this.V=g;this.ea=this.dvObj.Enums.TrafficScenario;this.ae=function(){var c=this.dataObj.Yb+"-"+this.dataObj.Vb;this.dataObj.isBrandShieldOrigin&&(c+="-bs");return c.replace(RegExp(",","g"),";")};this.uc=this.ae();this.U=e;this.L={N:{h:1,w:1},Cf:{h:10,w:10},Xe:10};115==this.dataObj.Rb&&
(this.L.N.h=20,this.L.N.w=20);this.dataObj.findclass&&1==this.dataObj.findclass&&this.qc.push("classDeclaration");this.searchByAdSrvId_8=function(c,b){k.a("a1");var d=/[0-9]+-[0-9]+-[0-9]+-[0-9]+/.exec(c);return null!=d&&(d=d.toString(),d.replace(RegExp("-","g"),"")==b)?!0:!1};this.Zb=this["searchByAdSrvId_"+(this.dataObj?this.dataObj.Rb||"":"")];this.getElementsByClassName=function(c,b){return p(c,function(c,a){k.a("ff1");var e=a.getElementsByClassName(c);k.a("ff1e");return"1"!=b?e:k.gc(e)})};this.querySelectorAll=
function(c,b){return p(c,function(c,a){k.a("ff3");var e=a.querySelectorAll("."+c);k.a("ff3e");return"1"!=b?e:k.gc(e)})};this.getElementsByTagName=function(c,b){return p(c,function(c,a){k.a("ff4");var e=a.getElementsByTagName(c);k.a("ff4e");return"1"!=b?e:k.gc(e)})};this.classDeclaration=function(){k.a("a9");var c="undefined"!==typeof window.document.getElementsByClassName,b="undefined"!==typeof window.document.querySelectorAll;if(!(1>this.dataObj.M.length)){var d=[];if(c)d=this.getElementsByClassName(this.dataObj.M,
this.dataObj.displaynon);else if(b)d=this.querySelectorAll(this.dataObj.M,this.dataObj.displaynon);else return;c=k.ta(d);for(b=0;b<c;b++)if(d[b]&&!this.pa(d[b])){var a=k.la(d[b]);if(a&&a.h>this.L.N.h&&a.w>this.L.N.w&&this.$(d[b])){this.f=d[b];break}}}};this.div=function(){if(!(1>this.dataObj.M.length))for(var c=this.getElementsByTagName("div",this.dataObj.displaynon),b=k.ta(c),d=0;d<b;d++)if(c[d]&&this.za(this.dataObj,c[d],!0)&&!this.pa(c[d])){var a=k.la(c[d]);if(a&&a.h>this.L.N.h&&a.w>this.L.N.w&&
this.$(c[d])){this.f=c[d];break}if((a=k.Hb(c[d],this.L.N.w,this.L.N.h,k.Wb(k.la,k)))&&this.$(a)){this.f=a;this.$(c[d]);break}}};this.span=function(){k.a("a10");if(!(1>this.dataObj.M.length))for(var c=this.getElementsByTagName("span",this.dataObj.displaynon),b=k.ta(c),d=0;d<b;d++)if(c[d]&&this.za(this.dataObj,c[d],!0)&&!this.pa(c[d])){if(this.Ke(c[d])){this.f=c[d];break}var a=k.Hb(c[d],this.L.N.w,this.L.N.h,k.Wb(k.la,k));if(a&&this.$(a)){this.f=a;this.$(c[d]);break}}};this.object=function(){k.a("a11");
for(var c=this.getElementsByTagName("object",this.dataObj.displaynon),b=k.ta(c),d=0;d<b;d++)if(c[d]&&this.za(this.dataObj,c[d])&&!this.pa(c[d])){var a=k.Hb(c[d],this.L.N.w,this.L.N.h,k.Wb(k.la,k));if(a&&this.$(a)){this.$(c[d]);this.f=a;break}}};this.embed=function(){k.a("a12");for(var c=this.getElementsByTagName("embed",this.dataObj.displaynon),b=k.ta(c),d=0;d<b;d++)if(c[d]&&this.za(this.dataObj,c[d])&&!this.pa(c[d])){var a=k.la(c[d]);if(a&&a.h>this.L.N.h&&a.w>this.L.N.w&&this.$(c[d])){this.f=c[d];
break}}};this.href=function(){k.a("a13");for(var c=this.getElementsByTagName("a",this.dataObj.displaynon),b=k.ta(c),d=0;d<b;d++)if(c[d]&&this.za(this.dataObj,c[d])&&!this.pa(c[d])){var a=c[d].getElementsByTagName("img");if(0<a.length){var e=k.la(a[0]);if(e&&e.h>this.L.N.h&&e.w>this.L.N.w&&this.$(c[d])){this.f=a[0];break}}}};this.img=function(){k.a("a14");for(var c=this.getElementsByTagName("img",this.dataObj.displaynon),b=k.ta(c),d=0;d<b;d++)if(c[d]&&this.za(this.dataObj,c[d])&&0>c[d].src.indexOf("event")&&
!this.pa(c[d])){var a=k.la(c[d]);if(a&&a.h>this.L.N.h&&a.w>this.L.N.w&&this.$(c[d])){this.f=c[d];break}}};this.iframe=function(){k.a("a15");for(var c=this.getElementsByTagName("iframe",this.dataObj.displaynon),b=k.ta(c),d=0;d<b&&!this.Cc(c[d]);d++);};this.frameElement=function(){k.a("a16");this.V==this.ea.SameDomain&&this.Cc(this.window.frameElement)};this.Cc=function(c){k.a("a17");return this.za(this.dataObj,c)?this.Qd(c):!1};this.$=function(c){k.a("a18");if(c&&0==this.pa(c))try{var b=c.getAttribute("dvvisit");
b?c.setAttribute("dvvisit",b+","+this.uc):(k.a("ff5"),b=this.window.document.createAttribute("dvvisit"),k.a("ff5e"),b.value=this.uc,c.setAttributeNode(b));return!0}catch(d){}return!1};this.bf=function(c){c&&c.hasAttribute&&c.hasAttribute("dvvisit")&&c.removeAttribute("dvvisit")};this.gf=function(){this.bf(this.f);this.f=null};this.pa=function(c){k.a("a19");if(c&&(c=c.getAttribute("dvvisit"))){c=c.split(",");for(var b=0;b<c.length;b++)if(c[b]==this.uc)return!0}return!1};this.Ke=function(c){k.a("a20");
return c&&"1"==c.getAttribute("adunit")?!0:!1};this.Qd=function(c){k.a("a21");if(c&&!this.pa(c)){var b=k.la(c);if(b&&b.h>this.L.N.h&&b.w>this.L.N.w&&this.$(c))return this.f=c,!0}return!1};this.za=function(c,b,d){k.a("a22");var a=null;return c.M&&0<c.M.length&&(this.Ac=1==c.Re?this.Ed:this.Ib,a=this.Kd(c,b,d))||!this.f&&(a=this.Ld(c,b))?!0:!1};this.Kd=function(c,b,d){k.a("a23");var a;try{if(c.Jc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(a=this.va(b.id,c.M))||(a=this.va(b.src,c.M));a||
(a=this.va(b.href,c.M));a||(a=this.va(b.getAttribute("flashvars"),c.M));a||(a=this.va(b.name,c.M));!a&&this.dataObj.findclass&&1==this.dataObj.findclass&&(a=this.va(b.getAttribute("class"),c.M));a||d||(a=this.va(b.innerHTML,c.M));a&&!d&&(a=this.Jd(c,b));return a}catch(e){return a}};this.Ld=function(c,b){k.a("a24");var d;try{if(c.Jc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(d=this.Ca(b.id,c))||(d=this.Ca(b.src,c));d||(d=this.Ca(b.href,c));d||(d=this.Ca(b.Hf,c));d||(d=this.Ca(b.name,c));
d||(d=this.Ca(b.innerHTML,c));return d}catch(a){return d}};this.Ca=function(c,b){k.a("a25");if(!c)return!1;c=c.toLowerCase();for(var d=0;d<this.Fb.length;d++){var a;if(b.Dc&&(a=(this.Fb[d][0]+b.Dc).toLowerCase(),a=c.indexOf(a),-1<a)||b.hd&&(a=(this.Fb[d][0]+b.hd).toLowerCase(),a=c.indexOf(a),-1<a))return!0}return!1};this.Jd=function(c,b){k.a("a26");return null==c.eb||""==c.eb?!1:this.va(this.Dd(b),c.eb)};this.Dd=function(c){k.a("a27");if(c.outerHTML)return c.outerHTML;for(var b=c.attributes.length,
d="",a=0;a<b;a++)d=d+c.attributes[a].nodeName+"="+c.attributes[a].nodeValue+" ";return d+c.innerHTML};this.va=function(c,b){k.a("a28");return!c||!b||5>b.length?!1:null!=(this.Ac?this.Ac(c,b):this.Ib(c,b))?!0:this.Zb&&"function"===typeof this.Zb?this.Zb(c,b):!1};this.Ed=function(c,b){k.a("a29");var d;try{d=(new RegExp(b)).exec(c)}catch(a){d=this.Ib(c,b)}return d};this.Ib=function(c,b){k.a("a30");var d=null;-1!==c.indexOf(b)&&(d=c);return d};this.he=function(c){k.a("a31");if(this.ue())return this.c.yd(),
this.kc||(this.kc=!0),this.f;if(this.dataObj.M&&0<this.dataObj.M.length&&!0===this.kc&&1<c)return this.f;"1"!=this.dataObj.displaynon&&(c=this.ve(),c.node&&(this.c.xd(c.Ga),this.f=c.node));return this.f};var m=[];this.ue=function(){k.a("32");if(this.dataObj.M&&0<this.dataObj.M.length){var c=this.qc.length,b=this.window,d=0,a=[];do{a.push(b.document);for(var e=a,g=b.document.getElementsByTagName("iframe")||[],f=0;f<g.length||25>f;f++){var l=null,l=k.se(g[f]);void 0!==l&&null!==l&&0==k.Le(l,e)&&e.push(l)}b=
k.le(b)}while(b&&10>++d);m=a;for(b=0;b<c;b++)if(this[this.qc[b]](),this.f){this.Ab=this.f;break}}return this.f};var q=[],u=["object","embed","img","iframe"];this.dataObj.spotXmode&&(u=["object","embed","video","iframe"]);this.Ne=function(c){k.a("a33");c=k.la(c);return this.Oe(c)};this.Oe=function(c){if(c){var b=c.w;c=c.h;for(var d=e.length,a=0,r=0;r<d;r++)if(15>=Math.abs(b-e[r].w))for(var a=e[r].h.length,g=0;g<a;g++)if(15>=Math.abs(c-e[r].h[g]))return!0}return!1};this.oe=function(){k.a("a34");return this.dataObj.isBrandShieldOrigin?
this.pe():this.qe()};this.qe=function(){k.a("a35");var b=(window.name||(window.frameElement?window.frameElement.id:"")).substr(7),e=window.parent;k.a("ff6");e=e.document.getElementsByTagName("script");k.a("ff6e");for(var d=e.length,a=0;a<d;a++)if(e[a]&&e[a].id&&e[a].id.substr(7)==b)return e[a];return null};this.pe=function(){k.a("a36");return this.dvObj.tags[this.dataObj.impressionId].tagElement};this.ve=function(){k.a("a37");var b=this.oe();return this.Vd(b)};this.Vd=function(b){k.a("a38");var e=
{node:b,Ga:0};b=[];for(q=[];e||0<b.length;){try{var d;a:{var a=e.node;try{if(a&&-1!=u.indexOf(a.nodeName.toLowerCase())){d=!0;break a}}catch(g){}d=!1}if(d&&this.Ne(e.node)&&!this.pa(e.node)&&this.$(e.node))return e;if(e.Ga<=this.L.Xe){var r,f=e.node,v=e.Ga,e=[],l=f.parentNode;l&&-1==q.indexOf(l)&&(q.push(l),e.push({node:l,Ga:v+1}));if(f.hasChildNodes())for(var m=0;m<f.childNodes.length;m++)f.childNodes[m]&&-1==q.indexOf(f.childNodes[m])&&1===f.childNodes[m].nodeType&&(q.push(f.childNodes[m]),e.push({node:f.childNodes[m],
Ga:v+1}));var p,w=f,U=[],z=null;w&&w.parentNode&&(z=w.parentNode.firstChild);for(;z;)1===z.nodeType&&z!==w&&U.push(z),z=z.nextElementSibling||z.nextSibling;p=U;for(m=0;m<p.length;m++)p[m]&&-1==q.indexOf(p[m])&&1===p[m].nodeType&&(q.push(p[m]),e.push({node:p[m],Ga:v+1}));if(r=e)for(e=0;e<r.length;e++)b.push(r[e])}}catch(g){}e=b.shift()}return{node:null}};return this}
function dv_CustomClientViewAssureService(b){function e(b){return{settings:b.settings,buckets:0,reported:!1,eventId:b.eventId,La:b.La,hb:b.hb}}this.dvObj=b.dvObj||window.$dv;this.impressionId=b.impressionId||window.$uid;this.b=new J;var f=[],l=null,g=null,p=null,k=null;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&(l=this.dvObj.tags[this.impressionId].cvmSettings,g=this.dvObj.tags[this.impressionId].billable,p=this.dvObj.tags[this.impressionId].bprjct,k=this.dvObj.tags[this.impressionId].gmmod);
this.xc=window.dv_cvmSettings||l||b.cvmSettings;this.Sb=window.dv_billable||g||b.billable;this.Ic=window.Jf||p||b.bprjct;this.Wc=window.Kf||k;this.be=new e({settings:this.xc,eventId:6,La:["CustomViewabilityViewable"]});var w=this.b.kb("rpv"),l=this.b.Pc().bgm;b.Ua=1==w&&1==l;this.Hc=new e({settings:this.Sb,eventId:17,La:b.Ua?["BillableViewedImpression"]:["BillableViewedImpression","GroupMPassedImpression"],hb:!0});this.xc&&f.push(this.be);this.Sb&&f.push(this.Hc);b.ma=b.ma||[];l={serverProperties:{projected:"bp",
viewed:"bpv",viewedRate:"bpvr",error:"bperr"},reportQueryString:{projected:"isbprjct",measurems:"isbmms",viewedms:"isbvms",viewrate:"prjctbvr",error:"prjctber"}};this.Ic&&(l={serverData:this.Ic,projectionData:l,reportRTN:!0},b.ma.push(l));l={serverProperties:{projected:"gmp",viewed:"gmpv",viewedRate:"gmpvr",error:"gmperr"},reportQueryString:{projected:"isgmmod",measurems:"isgmmims",viewedms:"isgmpims",viewrate:"modgmvr",error:"modgmer"}};this.Wc&&(l={serverData:this.Wc,projectionData:l,reportRTN:!0},
b.ma.push(l));this.Ud=dv_InViewService;this.Ud(b);var m=this.Jb;this.Jb=function(b){b=m(b);for(var c=0;c<f.length;c++){var e=this.Ce(b,f[c]);this.yf(e,f[c]);this.Sd(f[c])}return b};var q=this.Ma;this.Ma=function(b,c){q(b,c);this.Sb&&1==this.$b&&(this.ya(["BillableMeasuredImpression"]),w?0==this.dataObj.Ua&&this.ya(["GroupMMeasuredImpression"]):1!=this.dataObj.irtf&&this.ya(["GroupMMeasuredImpression"]))};this.Ce=function(b,c){"undefined"===typeof c.settings.focus||c.settings.focus||(b.i=b.ka);return b};
this.yf=function(b,c){(!c.settings.measureType||"consecutive"==String(c.settings.measureType).toLowerCase())&&b.i<c.settings.adArea?c.buckets=0:b.i>=c.settings.adArea&&(!c.hb||1!=this.dataObj.irtf)&&(c.buckets+=this.aa.interval);c.J=b.J};this.Sd=function(b){b.ff||b.hb&&1==this.dataObj.irtf||!(this.Md(b)||b===this.Hc&&b.settings&&!b.settings.doNotReportViewedOnLargeAd&&b.J)||(this.R.S(this.c.ba(b.eventId),b.eventId),b.La&&this.ya(b.La),b.ff=!0)};this.Md=function(b){return b.buckets>=b.settings.duration?
!0:!1}}
function dv_InViewService(b){function e(){null===g.interval&&(g.interval=setInterval(g.te(),g.aa.interval))}function f(){if(!1===g.dd){g.dd=!0;try{g.b.Ha.remove("load",arguments.callee,!1,element)}catch(a){}g.xb();g.b.a("s41");g.ua=new la(g.Xd?g.Xd:g.window,g.f,g.V,g.I,g.P,g.c.Ub,g.dvObj,g.impressionId);g.b.a("s42");g.Gd();g.start()}}function l(a,b){g.b.Ha.add("click",function(){g.Nb(!0);$dv.registerEventCall(g.impressionId,"ad"==b?{dvp_csad:1}:{dvp_csifr:1});g.b.Ha.remove("click",arguments.callee,!1,
a)},!1,a,!1)}var g=this;this.gd=10;this.Qb=b.serverSettings&&b.serverSettings.jsVersion?b.serverSettings.jsVersion:"624";this.dvObj=b.dvObj||window.$dv;this.impressionId=b.impressionId||window.$uid;this._minor_version="0";this.b=new J;this.De=function(){for(var a=document.getElementsByTagName("script"),b=a.length,c,d=0;d<b;d++)if(c=a[d].src,/visit[.]js/.test(c))return c.substring(c.indexOf("?")+1)};this.dd=!1;var p={serverProperties:{projected:"p",error:"perr",viewed:"pv",featurebit:"fb",viewedRate:"pvr"},
reportQueryString:{projected:"isprjct",measurems:"ismms",viewedms:"isiabvms",viewrate:"prjctvr",error:"prjcter"}},k=!1,w=!1;this.ma=b.ma||[];(this.zf=b.prjct)&&this.ma.push({serverData:b.prjct,projectionData:p,df:!0,Af:["MeasurementCapabilityDetected","ProjectedMeasured","IabView","ProjectedAssignedViewed"],Ye:["MeasurementCapabilityDetected","ProjectedMeasured"]});p={serverProperties:{projected:"up",error:"uperr",viewed:"upv",viewedRate:"upvr"},reportQueryString:{projected:"isuprjct",measurems:"isumms",
viewedms:"isuiabvms",viewrate:"uprjctvr",error:"uprjcter"}};this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].uprjct&&this.ma.push({serverData:this.dvObj.tags[this.impressionId].uprjct,projectionData:p});this.ye=function(){var a="";this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].tagElement&&(a=this.dvObj.tags[this.impressionId].tagElement.src,a=a.substring(a.indexOf("?")+1));return a};this.Vc=function(){return((new Date).getTime()+
""+Math.floor(1E6*Math.random())).substr(0,16)};this.ca=function(a,b){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var c=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec("?"+b);return c=c?c[1]:null};this.Ae=function(){var a=this.ca("uid",this.T);null==a?(a=this.Vc(),this.T=this.T+"&uid="+a):""==a&&(a=this.Vc(),this.T=this.T.replace("&uid=","&uid="+a));return a};this.rc=function(a,b,c,d){if(d&&d.insertBefore&&d.firstChild&&(a=this.window.document.createElement(a))){for(var e in b)a[e]=b[e];for(e in c)a.style[e]=
c[e];d.insertBefore(a,d.firstChild);return a}return null};this.Wd=function(){var a=this.dvObj.Enums.TrafficScenario;try{if(window.top==window)return a.OnPage;if(window.top.document.domain==window.document.domain)return a.SameDomain}catch(b){}return a.CrossDomain};this.V=this.dvObj.CommonData.Scenario||this.Wd();this.I={X:this.dvObj.CommonData.BrowserId,wa:this.dvObj.CommonData.BrowserVersion};this.Y=this.dvObj.Enums.BrowserId;this.ea=this.dvObj.Enums.TrafficScenario;this.Xa="default";this.dataObj=
b;this.window=b.tagWindow||parent.window||window;this.Ab=this.f=null;this.wc=this.Oa=!1;this.nc=!0;this.interval=null;this.T=this.De();this.zb=this.ye();this.af=b.serverSettings&&b.serverSettings.protocol&&0==b.serverSettings.protocol.indexOf("http")?b.serverSettings.protocol:window.location.protocol?window.location.protocol+"//":"http://";this.aa=window.ee||this.window.ee||{interval:100,Aa:{"default":{time:null,Ha:["beforeunload","unload"],td:9E5}}};this.jd={};var p="tps300.doubleverify.com",m=null;
try{this.dvObj.tags[this.impressionId].ServerPublicDns&&(p=this.dvObj.tags[this.impressionId].ServerPublicDns)}catch(a){}this.ia=window.dv_configServer||this.window.dv_configServer||{protocol:this.af,port:"",domain:p,api:"event.jpg"};this.W=window.de||this.window.de||{interval:1E3,da:6};p=b&&b.vd?b.vd:!1;b=b&&b.wd?b.wd:!1;!1!==p&&!1!==b&&(this.W.interval=p,this.W.da=b,$dv.registerEventCall(this.impressionId,{Ff:this.W.interval,Gf:this.W.da}));this.$d={gb:12,bc:10,Va:30};this.P={Firefox:{Z:115},Chrome:{Z:89},
Safari:{Z:38},Explorer:{Z:55},Ze:500,Va:30};var q=!1,u=0,c=[5,10,15];window.devicePixelRatio&&(this.P.Firefox.Z=0);this.dataObj.spotXmode=this.dataObj.videoEnable||this.dataObj.detectVideoPlayer||this.dataObj.spotXmode;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].spotXmode&&(this.dataObj.spotXmode=this.dvObj.tags[this.impressionId].spotXmode);this.U=window.dv_configAdSize||this.window.dv_configAdSize||[{w:300,h:[100,250,268,600,618,850,1050]},
{w:160,h:[600,800]},{w:120,h:[60,90,240,600,800]},{w:970,h:[66,90,250,30,415,550]},{w:728,h:[90,120]},{w:88,h:[31]},{w:700,h:[500]},{w:250,h:[60,250,300,360]},{w:180,h:[150,160,600]},{w:234,h:[60]},{w:468,h:[60]},{w:550,h:[480]},{w:125,h:[125]},{w:336,h:[280,600,850]},{w:745,h:[90]},{w:954,h:[60]},{w:184,h:[90]},{w:800,h:[600]},{w:320,h:[360]},{w:1280,h:[100]},{w:640,h:[480,90]},{w:270,h:[460,202]},{w:613,h:[460]},{w:405,h:[303]},{w:950,h:[90]},{w:610,h:[100]},{w:272,h:[220]},{w:200,h:[200,446]},
{w:220,h:[90]},{w:240,h:[133,400]},{w:960,h:[90]},{w:580,h:[400]},{w:750,h:[100,200,30]},{w:930,h:[180]},{w:980,h:[90,120]}];this.dataObj.spotXmode&&(this.U.push({w:320,h:[240]}),this.U.push({w:400,h:[300]}),this.U.push({w:450,h:[338]}),this.U.push({w:600,h:[800]}),this.U.push({w:640,h:[360]}),this.U.push({w:854,h:[480]}),this.U.push({w:500,h:[375]}));$dv&&$dv.CommonData&&(2==$dv.CommonData.deviceType||3==$dv.CommonData.deviceType)&&(this.U.push({w:320,h:[50,100,480]}),this.U.push({w:300,h:[50,31]}),
this.U.push({w:120,h:[20]}),this.U.push({w:168,h:[28]}),this.U.push({w:216,h:[36]}),this.U.push({w:292,h:[30]}));this.Xc=this.Ae();this.ac=!1;this.Gb=function(a,b){this.window.Mc||(this.window.Mc=[]);this.window.Mc.push({caller:a,If:b})};this.startTime=(new Date).getTime();this.Rd=4;this.Bc=0;this.hc=!0;this.logEvents={startMeasure:1,nonMeasurable:2,timeout:3,beforeunload:4,iabViewable:5,iabCustom:6,updateRTN:7,unload:8,projection:9,fraudMeasured:10,errorlevel1:16,Df:17,interval:32};this.$b=!1;this.ud=
function(){this.b.a("ie16");if(this.window.dv_logObject){var a=this.c.me();this.window.dv_logObject[this.Xc]=a}this.b.a("ie16e")};this.Bb=function(a){this.b.a("ie17");this.Bb=this.ac?function(a){this.c.od(a);this.ud()}:function(a){this.c.od(a)};this.Bb(a)};this.vc=function(a,b){this.vc=this.ac?function(a,b){this.c.nd(a,b);this.ud()}:function(a,b){this.c.nd(a,b)};this.vc(a,b)};this.xb=function(){this.b.a("s4");this.f=this.bb.he(this.W.da);this.Ab=this.bb.Ab;!this.f&&this.V==this.ea.CrossDomain&&this.b.xa(this.window)&&
(this.W.da=0);this.f?(this.jf(),this.c.cf(this.f),k||(l(this.f,"ad"),k=!0),w||this.V!=this.ea.CrossDomain&&this.V!=this.ea.SameDomain||(l(window.parent,"ifr"),w=!0),setTimeout(e,this.bb.kc?10:50)):0<this.W.da?(this.W.da--,this.kf(),setTimeout(this.ie(),this.W.interval)):(this.V==this.ea.CrossDomain&&(this.b.fd(this.window,this.U)||this.b.xa(this.window))?(this.f=this.b.Qa(this.window),this.c.md()):this.V==this.ea.SameDomain&&this.b.fd(this.window,this.U)?(this.f=this.b.Qa(window.parent),this.c.md(),
this.Zd()):this.W.da=-1,setTimeout(e,10));this.b.a("s4e")};this.Zd=function(){for(var a=this.window;a.parent!=a.top;)a=a.parent;this.b.a("ff26");for(var b=a.parent.document.getElementsByTagName("iframe"),c=b.length,d=0;d<c;d++)b[d].contentWindow==a&&(this.f=b[d],this.window=a.parent);this.b.a("ff26e")};this.kf=function(){this.dataObj.M&&this.dataObj.eb?this.c.pf():this.c.qf()};this.jf=function(){this.b.a("s9");this.Oa=!0;this.c.lf();this.b.a("s9e")};this.Td=function(){this.dataObj.Rb=this.ca("adsrv",
this.T)||"";this.dataObj.M=this.ca("btreg",this.T)||"";this.dataObj.hd=this.ca("plcid",this.T)||"";"8"==this.dataObj.Rb&&""==this.dataObj.btreg&&(this.dataObj.M=this.dataObj.plcid);this.dataObj.eb=this.ca("btadsrv",this.T)||"";this.dataObj.Dc=this.ca("adid",this.T)||"";this.dataObj.Re=this.ca("isbtregex",this.zb)||"";this.dataObj.Yb=this.ca("ctx",this.T)||"";this.dataObj.Vb=this.ca("cmp",this.T)||"";this.dataObj.Te=this.ca("lomd",this.T)||"";this.dataObj.findclass=this.ca("findclass",this.zb)||"";
this.dataObj.displaynon=this.ca("displaynon",this.zb)||"";this.dataObj.Jc=this.ca("bsdvview",this.zb)||""};this.Wa=function(a){a=this.ya(a);return 0<a.length?"&tagServiceResult="+encodeURIComponent(a.join(",")):""};this.ya=function(a){if(!this.dvObj||!this.impressionId)return[];for(var b=[],c=0;c<a.length;c++){var d=this.dvObj.pubSub.publish(a[c],this.impressionId)||null;null!=d&&b.push(d)}return b};this.He=function(a){1==a&&(this.c.wf(),this.dvObj&&this.impressionId&&this.c.mc()&&(a=this.Wa(["MeasurementCapabilityDetected",
"GeoMeasured"]),this.R.S(this.c.ba(this.logEvents.fraudMeasured)+a,this.logEvents.fraudMeasured)))};this.Ge=function(a){var b="",c=a.serverData,d=a.projectionData;1==c[d.serverProperties.featurebit]&&(b=1==c[d.serverProperties.viewed]?this.Wa(a.Af):this.Wa(a.Ye));return b};this.zd=function(){this.dataObj.serverSettings&&this.dataObj.serverSettings.TKH&&(this.T+="&TKH="+this.dataObj.serverSettings.TKH)};this.ce=function(){Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var b=
Object(this),c=b.length>>>0;if(0===c)return-1;var d=0;1<arguments.length&&(d=Number(arguments[1]),d!=d?d=0:0!=d&&Infinity!=d&&-Infinity!=d&&(d=(0<d||-1)*Math.floor(Math.abs(d))));if(d>=c)return-1;for(d=0<=d?d:Math.max(c-Math.abs(d),0);d<c;d++)if(d in b&&b[d]===a)return d;return-1}};this.inViewManager=function(){try{Array.prototype.indexOf||this.ce();var a=this.ia.protocol+this.ia.domain+this.ia.port+"/"+this.ia.api;this.zd();this.c=new aa(this.Qb,this.T,a,this.$d,this.dataObj);var b=new ba(this.window,
this.Xc);this.dataObj.isReportingDisabled?(X.prototype=b,this.R=new X):this.R=b;this.dataObj.isRTNsDisabled&&(this.ya=function(){return[]});this.ac=this.window.dv_logObject?!0:!1;this.rf();if(!this.c.Ub()&&(this.Fe(),void 0!=this.dataObj.prjct&&1==this.dataObj.prjct.p&&1==this.dataObj.prjct.fb))return;this.He(this.dataObj.irtf);this.Td();this.bb=new ma(this.dataObj,this.U,this.window,this.c,this.V);var c=window.parent;"589953"==this.dataObj.Yb&&"587351"==this.dataObj.Vb||"589953"==this.dataObj.Yb&&
"616389"==this.dataObj.Vb||"polite"==this.dataObj.Te?(setTimeout(f,15E3),this.b.Ha.add("load",function(){setTimeout(f,1E3)},!1,c,!1)):f()}catch(d){var e=this;this.Na(function(){e.Gb("inViewManager",d);e.c.sc("inViewManager",d);e.R.S(e.c.ba(e.logEvents.errorlevel1),e.logEvents.errorlevel1)},"inViewManager",d)}};this.Fe=function(){for(var a="",b=0;b<this.ma.length;b++){var c=this.ma[b];this.c.uf(c.serverData,c.projectionData);!0===c.df&&(a+=this.Ge(c))}0<this.ma.length&&this.R.S(this.c.ba(this.logEvents.projection)+
a,this.logEvents.projection)};this.$a=function(a){this.b.a("ie20");-6!=a.i&&(-3==a.i||-5!=a.i&&0>a.i&&-1==this.W.da)&&(this.yc(),this.$a=function(){})};this.yc=function(){this.R.S(this.c.ba(this.logEvents.nonMeasurable),this.logEvents.nonMeasurable);this.ya(["ImpressionNotMeasured"]);this.yc=function(){}};this.Ma=function(a,b){a.b.a("ie21");if(0<=b.i||-5==b.i&&-1>=a.W.da){if(a.dvObj&&a.impressionId&&0==a.c.mc()){a.b.a("ie23");var c=a.Wa(["MeasurementCapabilityDetected","GeoMeasured"]);a.b.a("ie24");
var d=a.c.ba(a.logEvents.startMeasure);a.R.S(d+c,a.logEvents.startMeasure)}else a.R.S(a.c.ba(a.logEvents.startMeasure),a.logEvents.startMeasure);a.$b=!0;a.Ma=function(){};a.$a=function(){}}a.b.a("ie22")};this.Nb=function(a){this.b.a("ie25");if(this.c.Qc()||a&&!0===a)this.b.a("ie27"),this.dvObj&&this.impressionId&&0==this.c.mc()?(this.b.a("ie28"),a=this.Wa(["IabView","GeoViewed"]),this.b.a("ie29"),this.R.S(this.c.ba(this.logEvents.iabViewable)+a,this.logEvents.iabViewable)):this.R.S(this.c.ba(this.logEvents.iabViewable),
this.logEvents.iabViewable),q=!0,this.Nb=function(){};this.b.a("ie26")};this.acumulateViewableTime=function(a){if(q&&this.c.Qc())for(u+=a,a=0;a<c.length;a++)null!=c[a]&&u>=1E3*c[a]&&(this.ya(["viewd"+c[a]+"sec"]),c[a]=null)};var h="hidden",d=0;this.hasFocus=function(){vis=["hidden","webkitHidden","mozHidden","msHidden","oHidden"];for(hiddenProp in vis)if(vis[hiddenProp]in document){h=vis[hiddenProp];break}var a=1==this.b.kb("fcs"),b=!1;try{this.b.Sa(this.window),b=!0}catch(c){}var e=!1;try{this.b.Sa(this.window.top),
e=!0}catch(c){}var f=null,f=a&&b&&this.I.X==this.Y.IE?function(){var a=g.b.Sa(g.window);g.V==g.ea.OnPage&&(a=a&&g.nc);return a}:a&&e?function(){var a=!0,a=g.b.Sa(g.window.top);g.V==g.ea.OnPage&&(a=a&&g.nc);return a}:"undefined"!==typeof document[h]?function(){return!g.window.document[h]}:e?function(){return g.b.Sa(g.window.top)}:function(){return!0};this.hasFocus=function(){try{return f()}catch(a){d++,5<=d&&(this.hasFocus=function(){return!0})}return!0};return this.hasFocus()};this.fc=function(a){var b=
a.ua.re();a.b.a("ie12");null==this.f||-3==b.i||a.hasFocus()||(b.i=0);a.b.a("ie13");return m=b};this.Jb=function(a){a.b.a("ie1");var b=a.f?a.f.ic||a.window:a.window;a.ua.f=a.f;a.ua.window=b;a.b.a("ie2");b=a.fc(a);a.Oa&&(-1==b.i||-2==b.i)&&-1<=a.W.da&&(a.ld(a),a.xb());a.b.a("ie3");-5==b.i&&(a.W.da--,a.c.pd(),a.Ka||(a.Ka=function(b){b=a.ua.rb(b);a.c.Za(b)}));a.b.a("ie4");a.Ka&&0<b.i&&(a.Ka(b),a.Ka=null);a.b.a("ie5");if(a.Oa&&!a.wc){a.wc=!0;var c=a.ua.rb(b);a.c.Za(c)}-5==b.i&&-1<=a.W.da&&(a.ld(a),a.xb(),
b=a.fc(a),-5==b.i&&0<a.W.da&&a.c.hf());a.b.a("ie6");a.vc(b,a.aa.interval);a.b.a("ie7");a.Bb(b);a.b.a("ie8");a.c.rd(b.ga);a.$a(b);a.b.a("ie9");a.Ma(a,b);a.b.a("ie10");a.Nb();a.b.a("ie11");a.acumulateViewableTime(a.aa.interval);a.b.a("ie12");return b};this.ld=function(a){a.Oa=!1;a.f=null;a.bb.gf();a.ua.Ie()};this.te=function(){this.b.a("s26");var a=this;return function(){try{a.Jb(a)}catch(b){a.Na(function(){a.Bc<a.Rd&&(a.Bc++,a.Gb("getIntervalCallback",b),a.c.sc("getIntervalCallback",b),a.R.S(a.c.ba(a.logEvents.errorlevel1),
a.logEvents.errorlevel1))},"getIntervalCallback",b)}}};this.Uc=function(a){var b=this;return function(){b.Na(function(){b.I.X==b.Y.IE?b.R.S(b.c.ba(b.logEvents[a]),b.logEvents[a]):b.R.Cb(b.c.ba(b.logEvents[a]),b.logEvents[a])},"getReportEventCallback")}};this.ie=function(){var a=this;return function(){a.Na(function(){a.xb();a.f||a.c.yb()},"getAdLocateCallback")}};this.Ra=function(){var a=this;return function(b){try{b||(b=a.window.event),a.nc="blur"==b.type||"focusout"==b.type?!1:!0}catch(c){try{b=
"",a.b?b=a.b.ob():a.b&&(b=a.b.ob()),a.R.S(a.ia.protocol+a.ia.domain+a.ia.port+"/"+a.ia.api+"?"+a.T+"&ctime="+(new Date).getTime()+"&evid="+a.logEvents.errorlevel1+"&jsver="+a.Qb+b+"&napr=getFocBluEventCallback: "+c.message,a.logEvents.errorlevel1)}catch(d){}}}};this.Fd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this;this.dvObj.tags[this.impressionId].getViewabilityData=function(){try{for(var b=a.c.ne().slice(0),c=0;c<b.length;c++)void 0===b[c]||null===
b[c]?b[c]=0:isNaN(b[c])||(b[c]/=1E3);var d={};d.bucket_0=b[0];d.bucket_1_9=b[1];d.bucket_100=b[11];for(c=2;10>=c;c++)d["bucket_"+(10*(c-1)).toString()+"_"+(10*c-1).toString()]=b[c];return{buckets:d,isAdMeasureable:a.$b,totalPageTime:(a.c.lb()-a.c.xe())/1E3,notApplicableTime:a.c.Tc()/1E3}}catch(e){return{}}}}}catch(b){}};this.Gd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this.dvObj.tags[this.impressionId];a.VA||(a.VA={});a.VA.getVisibilityResult=function(){var a=
{};a.perc=m.i;0<=m.i&&m.K&&m.K.j&&(a.adWidth=m.K.j.o,a.adHeight=m.K.j.m);return a};a.VA.getAdElem=function(){return g.f}}}catch(b){}};this.Fd();this.start=function(){this.b.a("s35");this.$e(this);var a;this.aa&&this.aa.Aa&&this.aa.Aa[this.Xa]&&(a=this.aa.Aa[this.Xa].Ha);if(a)for(var b=a.length,c=0;c<b;c++)this.jd[a[c]]=this.Uc(a[c]),this.Fa(this.window,a[c],this.jd[a[c]]);this.tf();this.aa&&this.aa.Aa&&this.aa.Aa[this.Xa]&&this.aa.Aa[this.Xa].td&&setTimeout(this.ef(),this.aa.Aa[this.Xa].td)};this.ef=
function(){var a=this;return function(){a.Uc("timeout")();clearInterval(a.interval);a.R.Cb=function(){};a.R.S=function(){}}};this.$e=function(a){try{var b=a.fc(a);-5==b.i&&(this.c.pd(),this.Ka||(this.Ka=function(b){b=a.ua.rb(b);a.c.Za(b)}));if(a.Oa)if(this.wc=!0,-5!=b.i){var c=a.ua.rb(b);a.c.Za(c)}else a.c.Za("true");a.c.rd(b.ga);var d=a.ua.ke(b,a.c.Tc());a.c.nf(d);a.c.qd(b.i);a.Bb(b);a.$a(b);a.Ma(a,b)}catch(e){a.Na(function(){a.Gb("onStartReport",e);a.c.sc("onStartReport",e);a.R.S(a.c.ba(a.logEvents.errorlevel1),
a.logEvents.errorlevel1)},"onStartReport",e)}};this.tf=function(){this.Fa(this.window,"blur",this.Ra());this.Fa(this.window,"focus",this.Ra());this.Fa(this.window.document,"click",this.Ra());this.Fa(this.window.document,"mousedown",this.Ra());this.Fa(this.window.document,"mouseup",this.Ra())};this.Fa=function(){function a(b,c,d){a=b.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:b.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:function(a,b,c){a["on"+b]=c};a(b,c,d)}return function(b,
c,d){a(b,c,d)}}();this.stop=function(){};this.rf=function(){this.b.a("ff24");this.V==this.ea.CrossDomain?this.b.xa(this.window)||this.b.lc(this.window)||this.b.sb()||this.b.tb(this.V,this.I,this.dvObj)||(this.I.X!=this.Y.Firefox&&this.I.X!=this.Y.IE?this.c.sf():this.I.X==this.Y.Firefox&&"undefined"===typeof this.window.mozInnerScreenX&&this.c.tc()):window.document.body.getBoundingClientRect||this.c.tc();this.hc=this.c.Ub();this.b.a("ff24e")};this.Na=function(a,b,c){try{a()}catch(d){try{if(0<this.gd){this.gd--;
var e=this.b.ob(),f=this.b.Rc(b||"unknown caller",c||d);this.R.S(this.ia.protocol+this.ia.domain+this.ia.port+"/"+this.ia.api+"?"+this.T+"&ctime="+(new Date).getTime()+"&evid="+this.logEvents.errorlevel1+"&jsver="+this.Qb+e+"&napr="+f,this.logEvents.errorlevel1)}}catch(g){}}};return this}
try{window.dv_InViewService=dv_InViewService;dv_InViewService.prototype.inViewManager=dv_InViewService.prototype.inViewManager;var ViewAssureBootstrapper=function(b){$dv.tags[$uid].gmmod||$dv.tags[$uid].cvmSettings||$dv.tags[$uid].billable||b.cvmSettings||b.billable?(new dv_CustomClientViewAssureService(b)).inViewManager():(new dv_InViewService(b)).inViewManager()};if("function"===typeof window.IVCallback)IVCallback(ViewAssureBootstrapper);else for(var na=[window.$dvbs,window.$dvbsr],Z=0;Z<na.length;Z++){var dvObj=
na[Z];if(dvObj&&"object"===typeof dvObj&&"function"===typeof dvObj.getTagObjectByService){var tagObject=dvObj.getTagObjectByService("avs624");if(tagObject){var serviceParams=tagObject.services.avs624;serviceParams&&serviceParams.params&&ViewAssureBootstrapper(serviceParams.params)}}}}catch(b){};
